# Generated by Django 6.0.6 on 2026-06-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_tier',
            field=models.CharField(choices=[('all', 'Semua'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='all', max_length=10, verbose_name='Target Tier'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='discount_sensitivity',
            field=models.CharField(choices=[('Not Sensitive', 'Not Sensitive'), ('Somewhat Sensitive', 'Somewhat Sensitive'), ('Highly Sensitive', 'Highly Sensitive')], max_length=30, verbose_name='Sensitivitas Diskon'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='education_level',
            field=models.CharField(choices=[('High School', 'High School'), ("Bachelor's", "Bachelor's"), ("Master's", "Master's"), ('PhD', 'PhD'), ('Other', 'Other')], max_length=20, verbose_name='Education Level'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non-binary'), ('Bigender', 'Bigender'), ('Genderfluid', 'Genderfluid'), ('Polygender', 'Polygender'), ('Agender', 'Agender'), ('Genderqueer', 'Genderqueer')], max_length=15, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='income_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Middle', 'Middle'), ('High', 'High')], max_length=10, verbose_name='Income Level'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=15, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='occupation',
            field=models.CharField(choices=[('Low', 'Low'), ('Middle', 'Middle'), ('High', 'High')], max_length=10, verbose_name='Occupation Level'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='purchase_channel',
            field=models.CharField(choices=[('Online', 'Online'), ('In-Store', 'In-Store'), ('Mixed', 'Mixed')], max_length=30, verbose_name='Channel Pembelian'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='purchase_intent',
            field=models.CharField(choices=[('Need-based', 'Need-based'), ('Wants-based', 'Wants-based'), ('Impulsive', 'Impulsive')], max_length=20, verbose_name='Niat Pembelian'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shipping_preference',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Express', 'Express'), ('No Preference', 'No Preference')], max_length=30, verbose_name='Preferensi Pengiriman'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='social_media_influence',
            field=models.CharField(choices=[('None', 'None'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20, verbose_name='Pengaruh Media Sosial'),
        ),
        migrations.AlterField(
            model_name='loyaltyprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loyaltyprofile',
            name='tier',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=10, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('PayPal', 'PayPal'), ('Cash', 'Cash'), ('Other', 'Other')], max_length=30, verbose_name='Metode Pembayaran'),
        ),
    ]
